const { app, BrowserWindow, ipcMain } = require('electron');
const net = require('net');
const path = require('path');
const { setupAutoUpdater } = require('./updater');

const HOST = '127.0.0.1';
const PORT = 6742;
const CLIENT_PROTOCOL = 5;
const TARGET_NAME = 'MSI MAG B550 TOMAHAWK';

function packet(dev, id, data = Buffer.alloc(0)) { const h=Buffer.alloc(16); h.write('ORGB',0,4,'ascii'); h.writeUInt32LE(dev>>>0,4); h.writeUInt32LE(id>>>0,8); h.writeUInt32LE(data.length>>>0,12); return Buffer.concat([h,data]); }
function ensure(b,o,n,what){if(o+n>b.length)throw new Error(`Resposta OpenRGB incompleta ao ler ${what}`)}
function u16(b,o){ensure(b,o,2,'u16');return b.readUInt16LE(o)}
function u32(b,o){ensure(b,o,4,'u32');return b.readUInt32LE(o)}
function i32(b,o){ensure(b,o,4,'i32');return b.readInt32LE(o)}
function readStr(b,o){const len=u16(b,o);ensure(b,o+2,len,'string');return{value:b.subarray(o+2,o+2+len).toString('utf8').replace(/\0+$/,''),next:o+2+len}}
function color(b,o){ensure(b,o,4,'cor');return{r:b[o],g:b[o+1],b:b[o+2]}}
function connect(timeout=1800){return new Promise((resolve,reject)=>{let settled=false;const s=net.createConnection({host:HOST,port:PORT});const finish=(fn,v)=>{if(!settled){settled=true;clearTimeout(timer);fn(v)}};const timer=setTimeout(()=>{s.destroy();finish(reject,new Error(`OpenRGB não respondeu em ${HOST}:${PORT}`))},timeout);s.once('connect',()=>finish(resolve,s));s.once('error',e=>finish(reject,e))})}
function readPacket(socket,wantedId,timeout=2200){return new Promise((resolve,reject)=>{let buf=Buffer.alloc(0),done=false;const timer=setTimeout(()=>finish(reject,new Error('Timeout aguardando resposta do OpenRGB SDK')),timeout);function finish(fn,v){if(done)return;done=true;clearTimeout(timer);socket.off('data',onData);socket.off('error',onError);fn(v)}function onError(e){finish(reject,e)}function onData(chunk){buf=Buffer.concat([buf,chunk]);while(buf.length>=16){if(buf.subarray(0,4).toString('ascii')!=='ORGB'){finish(reject,new Error('Cabeçalho SDK inválido (não é ORGB)'));return}const size=buf.readUInt32LE(12);if(buf.length<16+size)return;const p=buf.subarray(0,16+size);buf=buf.subarray(16+size);if(p.readUInt32LE(8)===wantedId){finish(resolve,p.subarray(16));return}}}socket.on('data',onData);socket.on('error',onError)})}
async function sdkRequest(id,dev=0,data=Buffer.alloc(0),responseId=id){const s=await connect();try{const pending=readPacket(s,responseId);await new Promise((r,j)=>s.write(packet(dev,id,data),e=>e?j(e):r()));return await pending}finally{s.end()}}
async function sdkSend(id,dev,data=Buffer.alloc(0)){const s=await connect();try{await new Promise((r,j)=>s.write(packet(dev,id,data),e=>e?j(e):r()));await new Promise(r=>setTimeout(r,35))}finally{s.end()}}
function protocolRequestData(proto){const b=Buffer.alloc(4);b.writeUInt32LE(proto>>>0,0);return b}
function parseMode(b,o,proto){let x=readStr(b,o),name=x.value;o=x.next;const modeValue=proto<6?i32(b,o):0;o+=proto<6?4:0;const flags=u32(b,o);o+=4;const speedMin=u32(b,o);o+=4;const speedMax=u32(b,o);o+=4;const brightnessMin=proto>=3?u32(b,o):0;o+=proto>=3?4:0;const brightnessMax=proto>=3?u32(b,o):0;o+=proto>=3?4:0;const colorsMin=u32(b,o);o+=4;const colorsMax=u32(b,o);o+=4;const speed=u32(b,o);o+=4;const brightness=proto>=3?u32(b,o):0;o+=proto>=3?4:0;const direction=u32(b,o);o+=4;const colorMode=u32(b,o);o+=4;const numColors=u16(b,o);o+=2;const colors=[];for(let i=0;i<numColors;i++){colors.push(color(b,o));o+=4}return{value:{name,modeValue,flags,speedMin,speedMax,brightnessMin,brightnessMax,colorsMin,colorsMax,speed,brightness,direction,colorMode,colors},next:o}}
function parseZone(b,o,proto){let x=readStr(b,o),name=x.value;o=x.next;const type=i32(b,o);o+=4;const min=u32(b,o);o+=4;const max=u32(b,o);o+=4;const count=u32(b,o);o+=4;const matrixLen=u16(b,o);o+=2;if(matrixLen){ensure(b,o,matrixLen,'matrix map');o+=matrixLen}const segments=[];if(proto>=4){const nseg=u16(b,o);o+=2;for(let i=0;i<nseg;i++){x=readStr(b,o);const segName=x.value;o=x.next;const segType=i32(b,o);o+=4;const start=u32(b,o);o+=4;const segCount=u32(b,o);o+=4;segments.push({name:segName,type:segType,start,count:segCount})}}const flags=proto>=5?u32(b,o):0;o+=proto>=5?4:0;return{value:{name,type,min,max,count,flags,segments},next:o}}
function parseController(body,proto){let o=0;const dataSize=u32(body,o);o+=4;if(dataSize>body.length-4)throw new Error('data_size do controlador é maior que a resposta recebida');const type=i32(body,o);o+=4;let x=readStr(body,o),name=x.value;o=x.next;const vendor=proto>=1?(x=readStr(body,o),o=x.next,x.value):'';x=readStr(body,o);const description=x.value;o=x.next;x=readStr(body,o);const version=x.value;o=x.next;x=readStr(body,o);const serial=x.value;o=x.next;x=readStr(body,o);const location=x.value;o=x.next;const numModes=u16(body,o);o+=2;const activeMode=i32(body,o);o+=4;const modes=[];for(let i=0;i<numModes;i++){const m=parseMode(body,o,proto);modes.push(m.value);o=m.next}const numZones=u16(body,o);o+=2;const zones=[];for(let i=0;i<numZones;i++){const z=parseZone(body,o,proto);zones.push(z.value);o=z.next}const numLeds=u16(body,o);o+=2;const leds=[];for(let i=0;i<numLeds;i++){x=readStr(body,o);leds.push(x.value);o=x.next;o+=proto<6?4:0}const numColors=u16(body,o);o+=2;const colors=[];for(let i=0;i<numColors;i++){colors.push(color(body,o));o+=4}const ledDisplayNames=[];if(proto>=5){const n=u16(body,o);o+=2;for(let i=0;i<n;i++){x=readStr(body,o);ledDisplayNames.push(x.value);o=x.next}}const flags=proto>=5?u32(body,o):0;return{type,name,vendor,description,version,serial,location,activeMode,modes,zones,leds,colors,ledDisplayNames,flags,ledCount:numLeds||numColors||zones.reduce((s,z)=>s+z.count,0)}}
async function getControllers(){let serverProtocol=0;try{const p=await sdkRequest(40,0,Buffer.alloc(0),40);serverProtocol=p.length>=4?p.readUInt32LE(0):0}catch(_){}const protocol=Math.min(serverProtocol||0,CLIENT_PROTOCOL);const countData=await sdkRequest(0,0,Buffer.alloc(0),0);if(countData.length<4)throw new Error('Resposta de quantidade de controladores inválida');const count=countData.readUInt32LE(0);if(count>256)throw new Error(`Quantidade de controladores inválida: ${count}`);const devices=[];for(let i=0;i<count;i++){const req=protocol>=1?protocolRequestData(protocol):Buffer.alloc(0);const d=await sdkRequest(1,i,req,1);devices.push({...parseController(d,protocol),index:i})}return{connected:true,serverProtocol,protocol,devices}}
function clamp(v,min,max){return Math.max(min,Math.min(max,Number(v)))}
function scaleColor(c,brightness){const s=clamp(brightness,0,100)/100;return{r:Math.round((c?.r??0)*s),g:Math.round((c?.g??0)*s),b:Math.round((c?.b??0)*s)}}
function makeUpdateLEDs(colors){const data=Buffer.alloc(6+colors.length*4);data.writeUInt32LE(2+colors.length*4,0);data.writeUInt16LE(colors.length,4);colors.forEach((c,i)=>{data[i*4+6]=c.r;data[i*4+7]=c.g;data[i*4+8]=c.b;data[i*4+9]=0});return data}
function serializeMode(mode,proto,brightness,speed,selectedColor){const parts=[];const name=Buffer.from(mode.name+'\0','utf8');const h=Buffer.alloc(2);h.writeUInt16LE(name.length,0);parts.push(h,name);if(proto<6){const b=Buffer.alloc(4);b.writeInt32LE(mode.modeValue|0,0);parts.push(b)}for(const value of [mode.flags,mode.speedMin,mode.speedMax]){const b=Buffer.alloc(4);b.writeUInt32LE(value>>>0,0);parts.push(b)}if(proto>=3)for(const value of [mode.brightnessMin,mode.brightnessMax]){const b=Buffer.alloc(4);b.writeUInt32LE(value>>>0,0);parts.push(b)}for(const value of [mode.colorsMin,mode.colorsMax]){const b=Buffer.alloc(4);b.writeUInt32LE(value>>>0,0);parts.push(b)}let b=Buffer.alloc(4);b.writeUInt32LE(Math.round(clamp(speed,mode.speedMin,mode.speedMax))>>>0,0);parts.push(b);if(proto>=3){b=Buffer.alloc(4);b.writeUInt32LE(Math.round(clamp(brightness,mode.brightnessMin,mode.brightnessMax))>>>0,0);parts.push(b)}for(const value of [mode.direction,mode.colorMode]){b=Buffer.alloc(4);b.writeUInt32LE(value>>>0,0);parts.push(b)}let colors=Array.isArray(mode.colors)?mode.colors.slice():[];if((mode.flags&64)!==0&&colors.length>0&&selectedColor)colors=colors.map(()=>selectedColor);const maxColors=mode.colorsMax||colors.length||1;const minColors=mode.colorsMin||0;if(colors.length<minColors)colors=Array.from({length:minColors},()=>selectedColor||{r:255,g:255,b:255});if(colors.length>maxColors)colors=colors.slice(0,maxColors);b=Buffer.alloc(2);b.writeUInt16LE(colors.length,0);parts.push(b);for(const c of colors){const cb=Buffer.alloc(4);cb[0]=c.r;cb[1]=c.g;cb[2]=c.b;cb[3]=0;parts.push(cb)}return Buffer.concat(parts)}
async function applyToDevice(device,cfg){const color=scaleColor(cfg.color,cfg.brightness);const effect=String(cfg.effect||'Cor fixa');if(effect==='Desligado'){if(!device.ledCount)return;await sdkSend(1050,device.index,makeUpdateLEDs(Array.from({length:device.ledCount},()=>({r:0,g:0,b:0}))));return}if(effect==='Cor fixa'){await sdkSend(1100,device.index,Buffer.alloc(0));await sdkSend(1050,device.index,makeUpdateLEDs(Array.from({length:device.ledCount},()=>color)));return}const requested=device.modes.find(m=>m.name.toLowerCase()===effect.toLowerCase())||device.modes.find(m=>m.name.toLowerCase().includes(effect.toLowerCase()));if(!requested)throw new Error(`Efeito "${effect}" não existe no controlador selecionado`);const modeData=serializeMode(requested,CLIENT_PROTOCOL,cfg.brightness,cfg.speed,color);const body=Buffer.alloc(8+modeData.length);body.writeUInt32LE(4+modeData.length,0);body.writeInt32LE(device.modes.indexOf(requested),4);modeData.copy(body,8);await sdkSend(1101,device.index,body)}
async function apply(cfg){const result=await getControllers();if(!result.devices.length)return{ok:false,reason:'no-device',protocol:result.protocol};const targetIndex=Number.isInteger(cfg.deviceIndex)?cfg.deviceIndex:null;let device=targetIndex!==null?result.devices.find(d=>d.index===targetIndex):null;if(!device)device=result.devices.find(d=>d.name.toUpperCase().includes(TARGET_NAME))||result.devices[0];if(!device)return{ok:false,reason:'no-device'};await applyToDevice(device,cfg);return{ok:true,device:{index:device.index,name:device.name},protocol:result.protocol}}
function createWindow(){const win=new BrowserWindow({width:1320,height:860,minWidth:980,minHeight:680,backgroundColor:'#0b0e13',webPreferences:{preload:path.join(__dirname,'preload.js'),contextIsolation:true,nodeIntegration:false,sandbox:false}});win.loadFile(path.join(__dirname,'index.html'))}
app.whenReady().then(()=>{createWindow();setupAutoUpdater({app,getWindow:()=>BrowserWindow.getAllWindows()[0],log:console.log})});
app.on('window-all-closed',()=>{if(process.platform!=='darwin')app.quit()});
ipcMain.handle('ping',()=>({ok:true,app:'Posto ARGB Control',version:app.getVersion(),packaged:app.isPackaged}));
ipcMain.handle('check-for-updates',async()=>{if(!app.isPackaged)return{ok:false,message:'Atualização automática só funciona na versão instalada.'};try{const{autoUpdater}=require('electron-updater');const result=await autoUpdater.checkForUpdates();return{ok:true,version:result?.updateInfo?.version||null}}catch(e){return{ok:false,message:e.message}}});
ipcMain.handle('detect',async()=>{try{return await getControllers()}catch(e){return{connected:false,devices:[],error:e.message}}});
ipcMain.handle('apply',async(_,cfg)=>{try{return await apply(cfg||{})}catch(e){return{ok:false,error:e.message}}});
